obj-$(CONFIG_DIAG_CHAR) := diagchar.o
obj-$(CONFIG_DIAG_SDIO_PIPE) += diagfwd_sdio.o
diagchar-objs := diagchar_core.o diagchar_hdlc.o diagfwd.o diagmem.o

obj-$(CONFIG_DEBUG_STATUS) += debug_status.o
obj-$(CONFIG_QXDM_LOG) += qxdm_log.o
